# Travis CI configuration file
# http://about.travis-ci.org/docs/
dist: trusty

language: python

# Available Python versions:
# http://about.travis-ci.org/docs/user/ci-environment/#Python-VM-images
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

# Dependencies installation commands
install:
  - pip install -U pip
  - pip install -r requirements-ci.txt

before_script:
  - "flake8 --config=config/flake8rc asm_collect.py asmtest tests"
  - "pylint --rcfile=config/pylintrc asm_collect.py asmtest tests"

script:
  - "python -m unittest discover"

notifications:
  email: false

sudo: false
branches:
  only:
    - master
git:
  depth: 300
